"use client";

import { useState } from "react";
import { BrainCircuit, Loader2, MessageCircleMore, Send } from "lucide-react";
import { Badge, Button, Card, Input } from "@/components/ui";
import { aiService } from "@/services";
import type { AiSupportChatResponse } from "@/types";

type ChatMessage = {
  role: "user" | "assistant";
  content: string;
};

const defaultPrompts = [
  "How do I track my order?",
  "I cannot login, what should I do?",
  "Payment succeeded but order not visible",
];

export function SupportChat() {
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [lastMeta, setLastMeta] = useState<AiSupportChatResponse | null>(null);

  async function sendMessage(message: string) {
    const text = message.trim();
    if (!text) return;

    setMessages((prev) => [...prev, { role: "user", content: text }]);
    setInput("");
    setLoading(true);

    try {
      const response = await aiService.supportChat({ message: text });
      setLastMeta(response);
      setMessages((prev) => [...prev, { role: "assistant", content: response.reply }]);
    } catch {
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content:
            "Support assistant is unavailable right now. Please email support@foodhub.app for urgent issues.",
        },
      ]);
      setLastMeta(null);
    } finally {
      setLoading(false);
    }
  }

  return (
    <Card className="space-y-4 border-emerald-200/70 bg-gradient-to-br from-emerald-50/60 via-white to-teal-50/60">
      <div className="flex items-start justify-between gap-3">
        <div className="space-y-1">
          <p className="inline-flex items-center gap-1 text-xs font-semibold uppercase tracking-[0.14em] text-emerald-700">
            <BrainCircuit className="size-3.5" /> AI Support Assistant
          </p>
          <h2 className="text-2xl">Need instant help?</h2>
          <p className="text-sm text-slate-600">
            Ask about login, orders, payments, reviews, or provider onboarding.
          </p>
        </div>
        <Badge className="bg-emerald-100 text-emerald-700">
          <MessageCircleMore className="mr-1 size-3.5" /> Smart help
        </Badge>
      </div>

      <div className="space-y-2">
        {messages.length === 0 ? (
          <p className="text-sm text-slate-600">Try a quick prompt:</p>
        ) : null}
        <div className="flex flex-wrap gap-2">
          {(lastMeta?.suggestions && lastMeta.suggestions.length > 0
            ? lastMeta.suggestions
            : defaultPrompts
          ).map((prompt) => (
            <Button
              key={prompt}
              type="button"
              variant="outline"
              size="sm"
              onClick={() => {
                void sendMessage(prompt);
              }}
              disabled={loading}
              className="rounded-full bg-white"
            >
              {prompt}
            </Button>
          ))}
        </div>
      </div>

      {messages.length > 0 ? (
        <div className="max-h-72 space-y-3 overflow-y-auto rounded-2xl border border-slate-200 bg-white/90 p-3">
          {messages.map((message, index) => (
            <div
              key={`${message.role}-${index}`}
              className={
                message.role === "user"
                  ? "ml-auto max-w-[85%] rounded-2xl bg-emerald-600 px-3 py-2 text-sm text-white"
                  : "mr-auto max-w-[85%] rounded-2xl bg-slate-100 px-3 py-2 text-sm text-slate-700"
              }
            >
              {message.content}
            </div>
          ))}
        </div>
      ) : null}

      {lastMeta ? (
        <div className="space-y-1">
          <div className="flex flex-wrap items-center gap-2 text-xs text-slate-500">
            <Badge className="bg-slate-100 text-slate-700">Intent: {lastMeta.intent}</Badge>
            <Badge className={lastMeta.source === "llm" ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"}>
              Source: {lastMeta.source}
            </Badge>
            {lastMeta.escalate ? (
              <Badge className="bg-rose-100 text-rose-700">Escalation recommended</Badge>
            ) : null}
          </div>
          <p className="text-xs text-slate-500">
            {lastMeta.source === "llm"
              ? "Response generated by Gemini-compatible LLM."
              : "Fallback support rules were used for this response."}
          </p>
        </div>
      ) : null}

      <form
        className="flex flex-col gap-2 sm:flex-row"
        onSubmit={(event) => {
          event.preventDefault();
          void sendMessage(input);
        }}
      >
        <Input
          value={input}
          onChange={(event) => setInput(event.target.value)}
          placeholder="Type your support question..."
          aria-label="Support chatbot input"
          className="h-11 bg-white"
          disabled={loading}
        />
        <Button type="submit" className="h-11 sm:px-5" disabled={loading}>
          {loading ? <Loader2 className="size-4 animate-spin" /> : <Send className="size-4" />}
          {loading ? "Thinking..." : "Send"}
        </Button>
      </form>
    </Card>
  );
}
