export const routes = {
  home: "/",
  about: "/about",
  contact: "/contact",
  help: "/help",
  privacy: "/privacy",
  terms: "/terms",
  meals: "/meals",
  mealDetails: (id: string) => `/meals/${id}`,
  providers: "/providers",
  providerDetails: (id: string) => `/providers/${id}`,
  login: "/login",
  register: "/register",
  authCallback: "/auth/callback",
  cart: "/cart",
  checkout: "/checkout",
  paymentSuccess: "/payment-success",
  dashboard: "/dashboard",
  customerDashboard: "/dashboard/customer",
  customerOrders: "/dashboard/customer/orders",
  customerOrderDetails: (id: string) => `/dashboard/customer/orders/${id}`,
  customerWishlist: "/dashboard/customer/wishlist",
  customerProfile: "/dashboard/customer/profile",
  providerDashboard: "/dashboard/provider",
  adminDashboard: "/dashboard/admin",
} as const;
